---
kind: pipeline
type: kubernetes
name: Lehtux Applications Deployment

defaults: &defaults
  image: quay.io/jlehtimaki/kubernetes-ci:v0.2.0

settings: &settings
  type: Baremetal
  kubectl_version: v1.20.2
  token:
    from_secret: k8s_token
  k8s_server:
    from_secret: k8s_server
  ca:
    from_secret: ca
  k8s_user: default
  actions: ["apply"]
  kustomize: true

steps:
  - name: Build
    image: plugins/docker
    pull: if-not-exists
    settings:
      username:
        from_secret: username
      password:
        from_secret: password
      registry: "quay.io"
      repo: "quay.io/jlehtimaki/toornament-csgo"
      tags: ${DRONE_COMMIT_SHA}
  - <<: *defaults
    name: Deployment
    settings:
      <<: *settings
      manifest_dir: k8s-resources
      image_version: ${DRONE_COMMIT_SHA}
      image: quay.io/jlehtimaki/toornament-csgo
      rollout_timeout: 5m
when:
  branch:
    - master
  event:
    - push
  exclude:
    - pull_request