---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toornament-csgo
  namespace: kanarod
spec:
  selector:
    matchLabels:
      app: toornament-csgo
  replicas: 1
  template:
    metadata:
      labels:
        app: toornament-csgo
    spec:
      containers:
        - name: toornament-csgo
          image: quay.io/jlehtimaki/toornament-csgo
          imagePullPolicy: IfNotPresent
          env:
            - name: GIN_MODE
              value: release
            - name: SEASON
              value: "9"
            - name: SEASON_ID
              value: "5161204601415041024"
            - name: FACEIT_API_KEY
              valueFrom:
                secretKeyRef:
                  key: faceit
                  name: toornament-csgo
            - name: TOORNAMENT_API_KEY
              valueFrom:
                secretKeyRef:
                  key: toornament
                  name: toornament-csgo
            - name: KANALIIGA_TOKEN
              valueFrom:
                secretKeyRef:
                  key: kanaliiga
                  name: toornament-csgo
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: access-token
                  name: toornament-csgo
          resources:
            limits:
              cpu: "0.1"
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: toornament-csgo
  namespace: kanarod
spec:
  selector:
    app: toornament-csgo
  ports:
    - port: 8080
      targetPort: 8080