name: CSGO Toornament Cloud Functiosn

on:
  push:
    branches:
      - "main"
    paths:
      - '.github/workflows/deploy.yml'
      - '*.go'
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: CSGO
          runtime: go116
          region: europe-west1
          env_vars: FACEIT_API_KEY=${{ secrets.FACEIT_API_KEY }},TOORNAMENT_API_KEY=${{ secrets.TOORNAMENT_API_KEY }},SEASON_ID=${{ secrets.TOORNAMENT_SEASON_ID }},KANALIIGA_TOKEN=${{ secrets.KANALIIGA_TOKEN }}
          credentials: ${{ secrets.GCP_SA_KEY }}

      # Example of using the output
      - id: test
        run: curl "${{ steps.deploy.outputs.url }}"